# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f8783f0d3961075150e7bf86413f78db8dc25f43cd619d1962b1db605806cc1790859c0721a0f6260413ca058195f533c42dc97367303ab4057f36ced58b83

test:
  secret_key_base: ea3f31edf9ed2fc0a659411ee0c18135496581812473774b3c0d2bca6d79fc590d677ecf62905aee601acf5075d8b6b227a5cc41c8948ad4705201fe7c9b38d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
